language:
  - cpp
  - python
services:
  - docker
env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="eloquent" #ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu BEFORE_SCRIPT='./scripts/ci_prebuild.sh' AFTER_SCRIPT='./scripts/ci_postbuild.sh'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script: 
  - source .industrial_ci/travis.sh
